### ISSUE TITLE
move from Selenium to Playwright?

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pybites-carbon#12]
This is annoying: https://github.com/PyBites-Open-Source/pybites-carbon/issues/5 and I wonder if this would not be an issue with Playwright ...

**Comment by amandanelson** [comment]
Can this use SeleniumBase instead? Driver download is automated/included

**Comment by bbelderbos** [comment]
Sure thing, the "driver getting out of sync" is the main concern for me here. If you do decide to take this up, let's close this issue and work on #5 - thanks!

**Comment by bbelderbos** [comment]
Thanks @amandanelson! Your PR https://github.com/PyBites-Open-Source/pybites-carbon/pull/13 fixes this too, no need to go with Playwright for now.

**Comment by bbelderbos** [comment]
Ran into the mismatch chrome browser and driver versions the other day, let's move Playwright, it seems more robust ...
