### ISSUE TITLE
update readme / how to best run with uv tools?

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pybites-carbon#18]
@cmsato09 FYI I added a console script back: https://github.com/PyBites-Open-Source/pybites-carbon/commit/75cfe4550a99063505ea43c4655f0c4ace566fd9

Is `uv tool run --from pybites-carbon carbon` indeed the best way now to run it?

```
√ pybites-carbon (main) $ uv tool install pybites-carbon -U
...
Installed 1 executable: carbon

# hm ...
√ pybites-carbon (main) $ uv tool run carbon
⠸ carbon==1.1.10                                                                                                                                                                                    error: Failed to download and build `carbon==1.1.10`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stderr]
Traceback (most recent call last):
...
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

?2 pybites-carbon (main) $ uv tool run pybites-carbon
The executable `pybites-carbon` was not found.
warning: An executable named `pybites-carbon` is not provided by package `pybites-carbon`.
The following executables are provided by `pybites-carbon`:
- carbon
Consider using `uv tool run --from pybites-carbon <EXECUTABLE_NAME>` instead.

?1 pybites-carbon (main) $ uv tool run --from pybites-carbon carbon
usage: carbon [-h] [-v] (-f CODE | -c | -s CODE) [-i] [-l LANGUAGE] [-b BACKGROUND] [-t THEME] [-d DESTINATION] [-w WT] [--driver-path DRIVER_PATH]
carbon: error: one of the arguments -f/--file -c/--clipboard -s/--snippet is required
```

**Comment by bbelderbos** [comment]
I think we need to update the readme: `pip install pybites-carbon`, this should say "in a venv" or use pipx, but then I would prefer `uv tool` as above

**Comment by bbelderbos** [comment]
I don't mind this alias in my .zshrc for now:

```
alias carbon="uv tool run --from pybites-carbon carbon"
```

> uv does behave differently here compared to pipx. With pipx, executables are symlinked directly to a common location, making them immediately accessible on the command line. However, uv treats tool-provided executables more conservatively, requiring --from to specify which package provides the executable. This setup is likely for dependency isolation within a single environment rather than directly exposing executables system-wide, which could conflict with existing package names.

**Comment by bbelderbos** [comment]
@cmsato09 FYI with eatlocal I don't have this issue, maybe because it's console script name (eatlocal) is unique? 

```
√ eatlocal (main) $ uv tool install eatlocal -U
Resolved 30 packages in 358ms
Prepared 1 package in 106ms
Uninstalled 1 package in 4ms
Installed 1 package in 4ms
 - eatlocal==1.0.0
 + eatlocal==1.1.0
Installed 1 executable: eatlocal
√ eatlocal (main) $ eatlocal --version
eatlocal 1.1.0
```

And with `carbon` unfortunately it collides with an existing pypi package 🤔

**Comment by cmsato09** [comment]
> @cmsato09 FYI I added a console script back: [75cfe45](https://github.com/PyBites-Open-Source/pybites-carbon/commit/75cfe4550a99063505ea43c4655f0c4ace566fd9)
> 
> Is `uv tool run --from pybites-carbon carbon` indeed the best way now to run it?
> 
> ```
> √ pybites-carbon (main) $ uv tool install pybites-carbon -U
> ...
> Installed 1 executable: carbon
> 
> # hm ...
> √ pybites-carbon (main) $ uv tool run carbon
> ⠸ carbon==1.1.10                                                                                                                                                                                    error: Failed to download and build `carbon==1.1.10`
>   Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
> 
> [stderr]
> Traceback (most recent call last):
> ...
> AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
> 
> ?2 pybites-carbon (main) $ uv tool run pybites-carbon
> The executable `pybites-carbon` was not found.
> warning: An executable named `pybites-carbon` is not provided by package `pybites-carbon`.
> The following executables are provided by `pybites-carbon`:
> - carbon
> Consider using `uv tool run --from pybites-carbon <EXECUTABLE_NAME>` instead.
> 
> ?1 pybites-carbon (main) $ uv tool run --from pybites-carbon carbon
> usage: carbon [-h] [-v] (-f CODE | -c | -s CODE) [-i] [-l LANGUAGE] [-b BACKGROUND] [-t THEME] [-d DESTINATION] [-w WT] [--driver-path DRIVER_PATH]
> carbon: error: one of the arguments -f/--file -c/--clipboard -s/--snippet is required
> ```

I saw something similar when running `uv tool run carbon -c`

```shell
The following executables are provided by `pybites-carbon`:
- carbon.exe
PS C:\Users\cmsato\VSCodeProjects\practice-playground> uv tool run carbon -c
   Built carbon==1.1.10
   Built txamqp==0.8.2
Installed 15 packages in 1.26s
```

The carbon 1.1.10 definitely refers to another PyPi package https://pypi.org/project/carbon/ and the txamqp package is a listed dependency for the other carbon. 

If I remember correctly, when uv runs a package name that isn't installed, it creates a temporary virtual environment and downloads it from pypi, runs the package, and cleans it up after it finishes running. So if I understand correctly, it will take the other carbon package and download it every time you try to run `uv tool run carbon` ?

Then it does make sense to use `uv tool run --from pybites-carbon carbon`. However, it seems like this isn't a problem when pybites-carbon is added as a dependency or dev dependency. I'm still able to use `uv run carbon` without downloading carbon=1.1.10.

**Comment by bbelderbos** [comment]
Interesting, thanks for investigating. 

We could also make the command unique then? `pbcarbon` or something? Or we just suggest the alias? 

I do think `uv tool` is the way to go for this right? And/or pipx?

I also need to update the dependency here btw https://github.com/bbelderbos/codeimag.es/blob/main/requirements.txt#L133
