### ISSUE TITLE
Support different webdrivers

### ISSUE THREAD

**Issue by GreatBahram** [PyBites-Open-Source/pybites-carbon#2]
Hi Bob,

How is it going? Have you thought of supporting different web drivers?

I did a bit of research, and it turns out they support the same functionality, but it turns out it requires a different configuration for each of them.

Thanks,

**Comment by bbelderbos** [comment]
Yo, not necessarily, do you see certain benefits adding this?

**Comment by GreatBahram** [comment]
For me, it is easier to work with Mozilla things rather than things made by Google. Secondly, I feel the geckodriver is available on most Linux platforms.

But I understand there are a couple of hassles to make this work, so if you feel it is not worth it, let's leave it as it is.

**Comment by bbelderbos** [comment]
Ah good point, did not consider that, might be worth the effort then. 
Is it hard to add? The selenium interface should work the same right?

**Comment by GreatBahram** [comment]
I didn't spend much time there, but, unfortunately, I spotted some differences at first glance.

**Comment by bbelderbos** [comment]
thanks, let's leave this open as a future enhancement then

**Comment by bbelderbos** [comment]
Will be covered / no longer needed with #14
